image: node:12-alpine
stages:
  - test
  - deploy

before_script:
  - yarn

Lint:
  stage: test
  script:
    - yarn lint
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^wip\-/ || $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != 'master'
      when: always

Test:
  stage: test
  script:
    - yarn test
  # only allowing failures for this right now since I don't have the unit tests actually setup.
  allow_failure: true
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^wip\-/ || $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != 'master'
      when: always

pages:
  stage: deploy
  script:
    - echo $PRODUCTION_CONFIG
    - mkdir configs && ls -l && cp $PRODUCTION_CONFIG configs/config.json
    - yarn generate
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
