image: node:16-alpine
stages:
  - test
  - deploy

before_script:
  - npm ci

Lint:
  stage: test
  script:
    - npm lint
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^wip\-/ || $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != 'master'
      when: always

Test:
  stage: test
  script:
    - npm test
  # only allowing failures for this right now since I don't have the unit tests actually setup.
  allow_failure: true
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^wip\-/ || $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != 'master'
      when: always

pages:
  stage: deploy
  script:
    - mkdir configs && cp $PRODUCTION_CONFIG configs/config.json
    - npm run generate
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
